<?php

namespace common\models;

use Yii;
use yii\base\Model;

class TeamMembersModel extends Model{
    public $name;
    public $Profile_image;
    public $designation;

    public $email;

    public $contact;
    public $occupation;


    public function formName()
    {
        return  ''; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['Profile_image'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],
            [['name', 'Profile_image', 'designation','occupation'], 'required'],
            [['created_on'], 'safe'],
            [['name', 'Profile_image', 'designation'], 'string', 'max' => 200],
            [['contact'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 100],
        ];
    }
}